environment_config:
  task_client:
    parameters:
      server_address: "http://127.0.0.1:8000/api"
  chat_history_item_factory_client:
    parameters:
      server_address: "http://127.0.0.1:8001/api"
  server_side_controller_address: "http://127.0.0.1:8003"
  interpreter_path: "/dev_data/cxd/anaconda3/envs/v311/bin/python"