language_model_dict:
  Llama-3.1-8B-Instruct:
    parameters:
      model_name_or_path: "/dev_data/cxd/nlp/model/meta-llama/Llama-3.1-8B-Instruct"
  DeepSeek-R1-Distill-Llama-8B:
    parameters:
      model_name_or_path: "/dev_data/cxd/nlp/model/deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
  DeepSeek-R1-Distill-Qwen-7B:
    parameters:
      model_name_or_path: "/dev_data/cxd/nlp/model/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
