import:
- ../../../../../../../definition.yaml
- ../../../../agent.yaml
- ../../task.yaml
assignment_config:
  callback_dict:
    callback_0:
      name: current_session_saving_callback
    callback_1:
      name: group_self_consistency_callback
      custom_parameters:
        language_model: Llama-3.1-8B-Instruct
        task_name:
          module: src.typings.TaskName
          parameters:
            value: db_bench
        inference_config_dict:
          do_sample: false
          num_beams: 1
          max_new_tokens: 512
          temperature: null
          top_k: null
          top_p: null
        group_count: 16
        sample_count_per_group: 4
  output_dir: outputs/{TIMESTAMP}
  sample_order: default
environment_config:
  use_task_client_flag: false
task_dict:
  db_bench:
    parameters:
      data_file_path: ./data/v0303/db_bench/processed/v0317_first1000/entry_dict.json
