assignment_config:
  language_model_list:
  - name: Llama-3.1-8B-Instruct
    custom_parameters:
      model_name_or_path: "/dev_data/cxd/nlp/model/meta-llama/Llama-3.1-8B-Instruct"
  agent:
    name: language_model_agent
    custom_parameters:
      language_model: Llama-3.1-8B-Instruct
      inference_config_dict:
        do_sample: false
        num_beams: 1
        max_new_tokens: 512
        temperature: null
        top_k: null
        top_p: null
